### ISSUE TITLE
Documentation feedback on /docs/self-hosted/ubuntu.rst

### ISSUE THREAD

**Issue by mwallet** [crate/crate-tutorials#102]
### Documentation feedback

 
- Page title: Ubuntu
- Page URL: https://cratedb.com/docs/crate/tutorials/en/latest/self-hosted/ubuntu.html
- Source: https://github.com/crate/crate-tutorials/blob/master/docs/self-hosted/ubuntu.rst

---

Please, add Ubuntu 22.04 (Jammy).

**Comment by amotl** [comment]
Dear Martijn,

thank you for writing in. I think we will need to improve that spot of the documentation.

In the meanwhile, I would like to kindly refer you to the documentation page at [^1], which outlines how to install on Ubuntu in a generic way.

I can see packages for Ubuntu 22 (Jammy) are being published already [^2]. Please report back if you encounter any problems using the outlined procedure.

With kind regards,
Andreas.

[^1]: https://cratedb.com/docs/crate/tutorials/en/latest/basic/index.html#debian-or-ubuntu
[^2]: https://cdn.crate.io/downloads/deb/stable/dists/jammy/

**Comment by amotl** [comment]
Dear Martijn,

the new installation documentation at https://cratedb.com/docs/guide/install/debian-ubuntu.html will no longer list names of supported Ubuntu versions explicitly, thus it will no longer create any kind of confusion.

Thanks again for your feedback on this, I am closing the ticket now.

With kind regards,
Andreas.
