### ISSUE TITLE
Documentation feedback on /docs/index.rst

### ISSUE THREAD

**Issue by michaelkremmel** [crate/crate-tutorials#103]
### Documentation feedback

 
- Page title: Installation
- Page URL: https://cratedb.com/docs/crate/tutorials/en/latest/index.html
- Source: https://github.com/crate/crate-tutorials/blob/master/docs/index.rst

---

I suggest to change the following sentence, since there is a typo in the word "required" and with CRFREE a free cluster is not limited to 30 days: "The easiest way to get started with CrateDB is to use a 30 day free CrateDB Cloud cluster, no credit card requrired."

**Comment by amotl** [comment]
Hi Michael,

thanks for your suggestion. I think you can create a quick-edit pull request directly from the browser. Can you try?

Thanks,
Andreas.

**Comment by michaelkremmel** [comment]
Thank you @amotl. I've tried now [here](https://github.com/crate/crate-tutorials/pull/105)

**Comment by seut** [comment]
Solved by https://github.com/crate/crate-tutorials/pull/105.
