### ISSUE TITLE
Missing documentation: Spinning up first CrateDB Instance with Docker

### ISSUE THREAD

**Issue by nomicode** [crate/crate-tutorials#16]
https://crate.io/docs/crate/tutorials/en/latest/getting-started/install-run/docker.html

leads to a 404 page

**Comment by nomicode** [comment]
@infoverload I created this issue based on feedback you gave

do you remember which page is linking here?

the docker instructions are here: https://crate.io/docs/crate/tutorials/en/latest/install-run/docker.html

**Comment by infoverload** [comment]
@mechanomi Should I create a rewrite rule in our Salt setup? To point https://crate.io/docs/crate/tutorials/en/latest/getting-started/install-run/docker.html to https://crate.io/docs/crate/tutorials/en/latest/install-run/docker.html ?

**Comment by nomicode** [comment]
@infoverload sounds good to me

**Comment by infoverload** [comment]
I have added the change to https://github.com/crate/salt/pull/2361
