### ISSUE TITLE
Instructions for install on Windows 10 don't work

### ISSUE THREAD

**Issue by nkev** [crate/crate-tutorials#42]
###  Documentation feedback

 
- Page title: Quick Install on Windows
- Page URL: https://crate.io/docs/crate/tutorials/en/latest/install-run/windows.html
- Source: https://github.com/crate/crate-tutorials/blob/master/docs/install-run/windows.rst

---

I followed the instructions in URL above to install `crate-4.4.2` on Windows 10 but no matter what I do I get the error `JAVA_HOME environment variable must be set` The variable **is** set:

```BASH
PS C:\WINDOWS\system32> cd "C:\Users\me\Downloads\crate-4.4.2"
PS C:\Users\me\Downloads\crate-4.4.2> ./bin/crate
JAVA_HOME environment variable must be set
PS C:\Users\me\Downloads\crate-4.4.2> $env:JAVA_HOME
C:\Program Files\Java\jdk-11.0.10
PS C:\Users\me\Downloads\crate-4.4.2> ./bin/crate.bat
JAVA_HOME environment variable must be set
PS C:\Users\me\Downloads\crate-4.4.2>
```
I restarted the computer and also I tried `crate.bat` instead with the same result. 
What am I doing wrong?

**Comment by amotl** [comment]
Hi Nuri,

I've just recognized your report here, but answered at https://github.com/crate/crate/issues/11110 before. Can you check my responses there? On the other hand, I handed in #43 in order to improve the setup instructions.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Nuri,

we just integrated #43. I hope the documentation is more concise now, and, more importantly after integrating crate/crate#11110 the other day, installation on Windows as outlined at [1] will even work properly now.

Thank you again for your reports.

With kind regards,
Andreas.

[1] https://crate.io/docs/crate/tutorials/en/latest/install-run/windows.html

**Comment by nkev** [comment]
Hi Andreas, 
Thank you for the amazing support!

**Comment by amotl** [comment]
Hi Nuri,

you are welcome, appreciate your feedback. As I see you might currently be evaluating CrateDB for your use case, if you didn't know that, I finally wanted to tell you that the CrateDB code base recently went completely open source, thus removing any restrictions on the former enterprise features like permissions, some aggregation functions, the 3-node use limit and more. See [1].

With kind regards,
Andreas.

[1] https://crate.io/press/entire-codebase-of-cratedb-open-source/

**Comment by nkev** [comment]
Thanks Andreas,

Yes, the initial announcement in February (and high support reputation) are the reasons I am evaluating CrateDB. I would like to use it not so much for IOT, but more a traditional GEO distributed RDMS (three nodes each in (US/EU/Asia). Are any customers using it this way? If so, could you please provide some use cases?

To give you more context, I am part of the global web team at Roland Corporation and I'm looking to replace our Kentico CMS (single global server for roland.com and other sites) with a custom distributed CMS capable of distributing files as well as data. Eventual consistency (maximum 2 minutes) is ok for our use case. We do have some complex joins but we should be able to refactor the schema and move some tables into embedded complex types, like array and object columns, moving closer to a document database. If CrateDB is the right solution we would probably use the Cloud version to take advantage of your scaling/support/expertise.

Am I on the right track or is CrateDB the wrong solution in your opinion?

**Comment by amotl** [comment]
Dear Nuri,

thank you for sharing some details about your use case. We will evaluate if CrateDB will fit your needs and come back to you. On this matter, may I humbly ask you to join our discussion forum at [1] and also post your question there? This space is much better suited for those kinds of discussions and beyond your specific request, it will also be a benefit for the community.

With kind regards,
Andreas.

[1] https://community.crate.io/

**Comment by amotl** [comment]
Dear Nuri,

while I don't know whether CrateDB would exactly fit the "GEO distributed RDBMS" description, I wanted to humbly connect you with @proddata and @SimonKingZA hereby. Maybe you will be happy to jump on a call with them in order to start an in-person discussion around your aims.

With kind regards,
Andreas.

**Comment by nkev** [comment]
Thanks Andreas,
It's very early in our evaluation, I just simply wanted to know if anybody was using CrateDB in this way.
If necessary, I will contact your colleagues down the line.
Thanks again.

**Comment by SimonKingZA** [comment]
Hey Nuri - simon@crate.io or hit me up here when you are ready/need any help in using crateDB or are even getting things headed towards production.
