### ISSUE TITLE
Link to docker troubleshooting guide does not exists

### ISSUE THREAD

**Issue by Kurpanik** [crate/crate-tutorials#44]
###  Documentation feedback

 
- Page title: Run on Docker
- Page URL: https://crate.io/docs/crate/tutorials/en/latest/install-run/docker.html
- Source: https://github.com/crate/crate-tutorials/blob/master/docs/install-run/docker.rst

---

![grafik](https://user-images.githubusercontent.com/71767601/112599559-67618f80-8e10-11eb-9299-17dafa401231.png)

**Comment by amotl** [comment]
Dear Alex,

thank you for reporting this. We just fixed a whole bunch of broken links on behalf of #45. I believe the broken link you've reported was amongst them and should now be working again.

With kind regards,
Andreas.
