### ISSUE TITLE
Bring back one-step setup instructions

### ISSUE THREAD

**Issue by amotl** [crate/crate-tutorials#51]
Hi again,

with #41, we removed the section outlining the usage of the wash & go installation program hosted at https://try.crate.io/.

```rst
.. _install-install-one-step:

One-step setup
==============

You can download and run CrateDB on many Linux distributions with one simple
command in your terminal application:

.. code-block:: console

   sh$ bash -c "$(curl -L https://try.crate.io/)"
```

However, people are explicitly signaling interest in such a program. @inviridi just told us at https://community.crate.io/t/installation-on-opensuse-fails/615/3:

> I can only guess how well your one-line script works, but let me say that it was the key reason for me to choose CrateDB over InfluxDB. If I spend hours learning about your product I might want to use it in my other projects as well. And then it is great if it is quick to install. Just my 0.02ct.

So, we added a patch https://github.com/crate/crate-utils/pull/46 in order to improve the situation. Attaching to that, I am thinking about whether it will be a good idea to bring back the respective documentation in an optimal way, accompanying the other setup variants.

With kind regards,
Andreas.

cc @proddata, @mfussenegger

**Comment by proddata** [comment]
On the fence, as the one-liner doesn't do much more than

- curl
- tar
- start

If that is not clear from the instructions yet, we might want to improve the ad-hoc instructions :)

**Comment by mfussenegger** [comment]
My opinion on this is covered by https://zignar.net/2020/03/10/install-scripts-a-not-so-good-idea/  :)

**Comment by inviridi** [comment]
> If that is not clear from the instructions yet, we might want to improve the ad-hoc instructions :)

Yes, that would be good. I was helped extremely swiftly in your forum but if I had known that I just had to unpack the file and start it, I hadn't even asked. 

Alternatively, you could also make a really cool installer that asks for an installation directory, checks for old versions, creates symlinks for systemd etc. In my book, the Node Red installer is benchmark if one does not want to package the files.

**Comment by proddata** [comment]
> Alternatively, you could also make a really cool installer that asks for an installation directory, checks for old versions, creates symlinks for systemd etc.

That's basically what we have for Debian, Ubuntu, RedHat, ... :)

**Comment by amotl** [comment]
Documentation about the ad hoc installation is [still there](https://cratedb.com/docs/guide/install/adhoc.html). Closing this now.
