### ISSUE TITLE
Create a simple introduction to sharding / partitioning.

### ISSUE THREAD

**Issue by proddata** [crate/crate-tutorials#55]
- Sharding is a core concept of CrateDB.
- I think every user should learn the very basics and be warned about bad practices before tinkering with CrateDB.
- This is not thought as a replacement for a good sharding guide, but only a short intro.

**Comment by mfussenegger** [comment]
Just to add to this:

In the past we had talked about adding an interactive tutorial to the admin ui that walks users through creating tables and then partitioning. Inspired by the vault web-ui tutorial.

**Comment by amotl** [comment]
Hi,

what @mfussenegger is referring to, is https://github.com/crate/crate-admin/issues/691. Indeed this will be nice but will require some effort. However, I also like having respective tutorials at hand, so thank you for working on #56 already.

With kind regards,
Andreas.
