### ISSUE TITLE
CrateDB installation instructions 

### ISSUE THREAD

**Issue by mfussenegger** [crate/crate-tutorials#60]
I think currently the installation instructions are not ideal.

In the [tutorial](https://crate.io/docs/crate/tutorials/en/latest/) there are several "Quick Install" sections. They're pretty minimal and the "next step" is then [first use](https://crate.io/docs/crate/tutorials/en/latest/first-use.html#use)

Then there is the [deployment](https://crate.io/docs/crate/howtos/en/latest/deployment/index.html) section with again installation instruction, this time per Distribution.

The configuration files that ship with the distributions include already good defaults for most important settings, but people who do a Tarball installation are not directed to crucial settings. Currently they're in the [Bootstrap](https://crate.io/docs/crate/howtos/en/latest/admin/bootstrap-checks.html#tarball) section.

Given that the bootstrap checks are not mandatory when CrateDB is not bound to a public network interface this is not always discovered. Not having the right values set for `max_map_count` can cause CrateDB to crash with "Native memory allocation (mmap)" errors, leading to a poor first experience.

**Comment by nomicode** [comment]
@mfussenegger thanks for the issue report!

I believe I understand your suggestion for improving the tarball installation docs. however, you also mention the quick install and first use docs as well as the deployment docs. do you have suggestions for how to improve those?

**Comment by mfussenegger** [comment]
I mentioned them because I think it might make sense to change the structure altogether somewhat

Currently some of the information feels redundant and there is no clear path for people who want to setup CrateDB for production.

I didn't think too much about how it should or could look like, but the current state doesn't feel ideal

**Comment by proddata** [comment]
I think we should remove the "quick install" all together and show the "correct" way to install/start CrateDB from the beginning.

**Comment by nomicode** [comment]
@proddata the goal of the tutorials section is to give people an easy way to get some initial "wins" with CrateDB, to help people get familiar with (and feel successful with) the product. or to put it another way, too "hook" them with some initial easy-to-follow instructions and easy-to-recreate experiences. the problem with the "correct" way to install CrateDB is that it is complex. if we jump right into advising people on how to start a production-grade cluster is that we risk turning people away before they have any experience with the product

**Comment by proddata** [comment]
@mechanomi 
I get that this is the general idea, but it highly doubt it is happening. I wouldn't even touch the try-script, if I haven't first looked through it.

> the problem with the "correct" way to install CrateDB is that it is complex

I think the "correct" way is more straight forward for users

e.g. with apt ... 
```sh
wget https://cdn.crate.io/downloads/deb/DEB-GPG-KEY-crate
sudo apt-key add DEB-GPG-KEY-crate
sudo add-apt-repository "deb https://cdn.crate.io/downloads/deb/stable/ $(lsb_release -cs) main"
sudo apt install crate
```

e.g. with docker
```sh
docker run -p "4200:4200" -p "5432:5432" crate
```

**Comment by nomicode** [comment]
I see two potential work items here:

- Fix the tarball installation instructions per @mfussenegger's comments
- Re-work our approach to onboarding first-time users

for the first item, I think I can tackle that on my own

for the second, we need more planning

@proddata, you've brought this topic up before, but I don't remember where we left off. a good first step would be to propose a new navigation structure (top-level docs projects, 1st-level pages, 2nd-level pages, and so on). from there, we can move on to proposing outlines for the individual documents. that would help me understand your suggestions and would give us something concrete to discuss

**Comment by proddata** [comment]
maybe a suggestion to simplify he bloated install instructions: crate/crate-tutorials/pull/41

**Comment by nomicode** [comment]
@proddata can you please confirm whether https://github.com/crate/crate-tutorials/pull/41 closes this issue? I will add my own PR later to add my own changes. but I would like to close this issue out now if you think your PR does the job

**Comment by proddata** [comment]
@norosa 
I think the #41 solved part of the issue, as now https://crate.io/docs/crate/howtos/en/latest/deployment/linux/index.html probably also should be reworked and focus more on configuration / upgrading / troubleshooting with the respective systems. If we close it, we probably should add a new issue.

Then again I'd also be happy to get your input/feedback on the overall installation topic.

**Comment by nomicode** [comment]
@proddata okay, thanks for the feedback. I think that would probably make sense as a new issue in crate/crate-howtos, if for no other reason than to align the issue with the correct repo

will leave this issue for you to close if you agree and after the new issue is made
