### ISSUE TITLE
URL redirects for getting-started to tutorials

### ISSUE THREAD

**Issue by jayeff** [crate/crate-tutorials#62]
I noticed that some of the getting-started URL rewrites don't redirect to the new tutorial section of our docs.

I opened a PR for updating the URLs in crate/crate (see https://github.com/crate/crate/pull/11212) but probably we need a slight overall over the current redirect rules.

I would expect that I `getting-started` urls redirect me to the appropriate page in the `tutorials` section. If this is not possible I think [Tutorials overview page](https://crate.io/docs/crate/tutorials/en/latest/index.html) is best. 

Current behaviour seems to be for getting-started to redirect to reference start page:
e.g. https://crate.io/docs/crate/getting-started/en/latest/connect/index.html => https://crate.io/docs/crate/reference/en/4.5/index.html

Also it seems we are missing some redirects for old tutorials links
https://crate.io/docs/crate/tutorials/en/latest/getting-started/install-run/index.html => 404

_Note: copied over from https://github.com/crate/tech-writing-domain/issues/393_

**Comment by nomicode** [comment]
@jayeff thanks for the bug report! https://github.com/crate/salt/pull/2548 should fix these issues
